# -*- coding: utf-8 -*-
"""
Created on Wed Aug 16 10:53:52 2017

@author: Anne-Julie Tinet

The class Parameters contains all physical parameters for one zone (flow type
and reach) of the domain, namely :
    
    - area of the zone [L^2]
    - dispersivity     [L^2 / T], the dispersivity is considered constant
    - exchange rates   [L^2 / T], the exchange rate is generated by the method setAlpha
it relates 2 zones
    - Degradation rate [1/T], the degradation rate is considered constant
    - Lateral inflow  [L^2 / T], inflow of the domain
	- Lateral outflow  [L^2 / T], outflow of the domain
    - Lateral concentration [CU], equilibrium concentration constraining the
in/out flow

"""

import numpy as np


class Parameters:
    """Contains all physical parameters for one zone (flow type and reach) of
    the domain."""
    
    def __init__(self,area, dispersivity, degradation, qlin, qlout, clin):   
        self.A_ = area
        self.D_ = dispersivity
        self.alpha_ = {}
        self.lambda_ = degradation
        self.ql_ = qlin
        self.qlout_ = qlout
        self.cl_ = clin
        
    def setAlpha(self,alpha):
        self.alpha_ = alpha.copy()
        
    def getArea(self):
        return self.A_
        
    def getAlpha(self):
        return self.alpha_
        
    def getLambda(self):
        return self.lambda_
        
    def getLateral(self):
        return self.ql_,self.cl_
        
    def getLateralOut(self):
        return self.qlout_
        
    def getD(self):
        return self.D_